const allQuestions = [
    // --- MATHEMATICAL REASONING TRAPS ---
    { q: "The probability of at least one '6' in four rolls of a single fair die is approx?", a: "0.518", options: ["0.166", "0.518", "0.666", "0.750"] },
    { q: "A clock shows 3:25. What is the exact internal angle between the hands?", a: "47.5°", options: ["30°", "47.5°", "60°", "52.5°"] },
    { q: "A bat and ball cost $1.10. The bat costs $1.00 more than the ball. Cost of ball?", a: "$0.05", options: ["$0.10", "$0.05", "$0.01", "$0.15"] },
    { q: "A cube's side is increased by 10%. By what percentage does the volume increase?", a: "33.1%", options: ["10%", "30%", "33.1%", "21%"] },
    { q: "If you have a drawer with 10 black and 10 blue socks, what is the minimum you must pull to guarantee a matching pair?", a: "3", options: ["2", "3", "11", "21"] },
    { q: "Seven people meet and each shakes hands with everyone else once. Total handshakes?", a: "21", options: ["49", "42", "21", "14"] },
    { q: "A 4-bit R-2R ladder DAC uses Vref=10V. Smallest output change (LSB)?", a: "0.625V", options: ["0.625V", "1.25V", "2.5V", "0.312V"] },
    
    // --- NEW TOUGH MATH ADDITIONS (Batch 1) ---
    { q: "If a squirrel flies 20m in 2s with 5m/s tailwind, what is its speed in still air?", a: "5m/s", options: ["10m/s", "5m/s", "15m/s", "7.5m/s"] },
    { q: "What is the next number in the prime sequence: 2, 3, 5, 7, 11, ...?", a: "13", options: ["12", "13", "15", "17"] },
    { q: "If 7 people can build 7 houses in 7 months, how many months for 1 person to build 1 house?", a: "7", options: ["1", "7", "49", "0.7"] },
    { q: "A man is twice as old as his son. 10 years ago he was 3 times as old. How old is the son now?", a: "20", options: ["15", "20", "25", "30"] },
    { q: "If 1.1 raised to the power of X is 1.21, what is X?", a: "2", options: ["1.1", "2", "10", "1.21"] },

    { q: "Introduce a girl, a boy said: 'She is the daughter of the mother of my mother.' Who?", a: "Maternal Aunt", options: ["Sister", "Mother", "Maternal Aunt", "Cousin"] },
    { q: "How many cubic feet of dirt are in a hole 3ft deep and 3ft wide?", a: "0", options: ["27", "9", "0", "3"] },
    { q: "What is the result of '5' + 3 in JavaScript?", a: "'53'", options: ["8", "'53'", "NaN", "Error"] },
    { q: "Binary 101101 to Decimal?", a: "45", options: ["45", "43", "37", "41"] },
    { q: "Pointing to a boy, Meena says: 'He is son of my father's only son.' Meena is his?", a: "Aunt", options: ["Mother", "Sister", "Aunt", "Grandmother"] },
    { q: "What is 3/7 chicken, 2/3 cat, and 2/4 goat?", a: "Chicago", options: ["Animal", "Chicago", "Chimera", "Chaos"] },
    { q: "If A+B means A is daughter of B, what is P+Q+R?", a: "P is granddaughter of R", options: ["P is sister", "P is granddaughter of R", "P is mother", "None"] },

    // --- NEW TOUGH MATH ADDITIONS (Batch 2) ---
    { q: "In a class of 50, 30 like tea and 25 like coffee. Minimum who like both?", a: "5", options: ["0", "5", "10", "15"] },
    { q: "A clock strikes 4 in 6 seconds. How many seconds will it take to strike 8?", a: "14", options: ["12", "14", "16", "18"] },
    { q: "What is the remainder when 2 to the power 10 is divided by 3?", a: "1", options: ["0", "1", "2", "3"] },
    { q: "If a car travels at 60km/h for 30km and 30km/h for the next 30km, average speed?", a: "40km/h", options: ["45km/h", "40km/h", "50km/h", "35km/h"] },

    { q: "What is the thermal voltage (Vt) at room temperature (300K) approx?", a: "26 mV", options: ["26 mV", "0.7 V", "1 V", "12 mV"] },
    { q: "Which component resists the flow of current?", a: "Resistor", options: ["Capacitor", "Inductor", "Resistor", "Diode"] },
    { q: "Introducing a girl, a boy said: 'She is the daughter of the mother of my mother.' Who?", a: "Maternal Aunt", options: ["Sister", "Mother", "Maternal Aunt", "Cousin"] },
    { q: "Which memory is used to store the BIOS?", a: "ROM", options: ["RAM", "ROM", "Cache", "HDD"] },
    { q: "A gardener plants 10 trees in 5 rows with 4 trees in each row. How?", a: "Star shape", options: ["Circle", "Star shape", "Square", "Impossible"] },
    { q: "The wavelength of a 1GHz signal in air is approximately?", a: "30 cm", options: ["3 m", "30 cm", "3 cm", "300 m"] },
    { q: "The 2026 Winter Olympics are in?", a: "Milano Cortina", options: ["Beijing", "Milano Cortina", "Paris", "Tokyo"] },
    { q: "HTML tag for the largest heading?", a: "h1", options: ["head", "h6", "heading", "h1"] },
    { q: "Total number of squares on a standard Chessboard?", a: "204", options: ["64", "204", "128", "256"] },

    // --- NEW TOUGH MATH ADDITIONS (Batch 3) ---
    { q: "The ratio of father's age to son's is 7:3. Sum of ages is 60. Father's age?", a: "42", options: ["35", "40", "42", "45"] },
    { q: "A bag has 5 red and 3 blue balls. Probability of picking blue then red without replacement?", a: "15/56", options: ["15/64", "15/56", "8/15", "1/2"] },
    { q: "If 'POWER' is coded as 77, what is 'WORK' coded as?", a: "67", options: ["60", "67", "70", "77"] },
    { q: "How many degrees does the hour hand move in 20 minutes?", a: "10°", options: ["10°", "20°", "120°", "5°"] },

    { q: "If the Fermi level in a semiconductor moves closer to the conduction band, the material is?", a: "N-type", options: ["P-type", "N-type", "Intrinsic", "Insulator"] },
    { q: "If the radius of Earth is halved but mass is constant, what happens to 'g'?", a: "Increases 4x", options: ["Doubles", "Increases 4x", "Halves", "Constant"] },
    { q: "Angle between clock hands at 3:25?", a: "47.5°", options: ["30°", "47.5°", "60°", "52.5°"] },
    { q: "The probability of at least one '6' in four rolls of a single fair die is approx?", a: "0.518", options: ["0.166", "0.518", "0.666", "0.750"] },
    { q: "Looking at a portrait, X says: 'She is the mother of my wife's mother-in-law.' Who?", a: "X's Grandmother", options: ["X's Mother", "X's Grandmother", "X's Mother-in-law", "None"] },
    { q: "What does SQL stand for?", a: "Structured Query Language", options: ["Simple Query Logic", "Structured Query Language", "System Query List", "None"] },
    { q: "What is seen in the middle of March and April that can’t be seen at the start?", a: "The letter R", options: ["Spring", "Rain", "The letter R", "Sun"] },
    { q: "The work done in moving a charge of 2C across a 12V potential is?", a: "24 J", options: ["6 J", "24 J", "10 J", "0.16 J"] },
    { q: "Binary 11111111 (8 bits) in Decimal?", a: "255", options: ["256", "255", "127", "254"] },
    { q: "Which sorting algorithm is O(n) in best case?", a: "Insertion Sort", options: ["Quick Sort", "Merge Sort", "Insertion Sort", "Selection Sort"] },
    { q: "In binary shift, what is 10 >> 1?", a: "5", options: ["20", "5", "100", "1"] },
    { q: "Which nation chaired the 2025 BRICS summit?", a: "Brazil", options: ["Russia", "Brazil", "South Africa", "India"] },
    { q: "Pointing to a man, a girl says: 'He is the son of my grandfather's only child.' Who is he?", a: "Brother", options: ["Father", "Brother", "Cousin", "Uncle"] },
    { q: "Two mothers and two daughters go out to dinner. They only order 3 meals. Why?", a: "Grandmother, mother, daughter", options: ["Not hungry", "Baby", "Grandmother, mother, daughter", "Error"] },
    { q: "Successive discounts of 20% and 10% equal a single discount of?", a: "28%", options: ["30%", "28%", "25%", "22%"] },
    { q: "A clock loses 10 mins every hour. It was set right at 12 PM. Time at real 6 PM?", a: "5 PM", options: ["5 PM", "5:10 PM", "6:50 PM", "7 PM"] },
    { q: "Which language is used for Web styling?", a: "CSS", options: ["HTML", "Python", "CSS", "SQL"] },
    { q: "How many 9s are there between 1 and 100?", a: "20", options: ["10", "11", "19", "20"] },
    { q: "Anita is twice as old as Ben. 10 years ago she was 3x his age. Anita's current age?", a: "40", options: ["20", "30", "40", "50"] },
    { q: "What does BIOS stand for?", a: "Basic Input Output System", options: ["Binary Input OS", "Basic Input Output System", "Basic Integrated OS", "None"] },
    { q: "A man has 6 daughters. Each has one brother. Total children in family?", a: "7", options: ["12", "7", "6", "13"] },
    { q: "Which company owns Android?", a: "Google", options: ["Apple", "Microsoft", "Google", "Nokia"] },
    { q: "What protects a circuit from overcurrent?", a: "Fuse", options: ["Fuse", "Switch", "Transformer", "Inverter"] },
    { q: "How many 1cm cubes fit inside a 1m cube?", a: "1,000,000", options: ["100", "10,000", "1,000,000", "1,000"] },
    { q: "If 'POWER' is 77, what is 'WORK'?", a: "67", options: ["46", "67", "57", "68"] },
    { q: "Which scheduling algorithm can lead to Starvation?", a: "Priority", options: ["Round Robin", "Priority", "FIFO", "Shortest Job First"] },
    { q: "Ohm's Law: If Resistance doubles, Current...?", a: "Halves", options: ["Doubles", "Halves", "Triples", "Stays same"] },
    { q: "Which sensor is used to detect light?", a: "LDR", options: ["LDR", "PIR", "Ultrasonic", "Gyroscope"] },
    { q: "Who is the 'Father of AI'?", a: "John McCarthy", options: ["Alan Turing", "John McCarthy", "Elon Musk", "Bill Gates"] },
    { q: "Square of 25 plus square of 15?", a: "850", options: ["625", "850", "400", "725"] },
    { q: "In binary shift, what is 10 >> 1?", a: "5", options: ["20", "5", "100", "1"] },
    { q: "If A+B means A is daughter of B, what is P+Q+R?", a: "P is granddaughter of R", options: ["P is sister", "P is granddaughter of R", "P is mother", "None"] },
    { q: "If 3 cats kill 3 rats in 3 minutes, how many cats to kill 100 rats in 100 minutes?", a: "3", options: ["100", "33", "3", "10"] },
    { q: "A 100W bulb is on for 10 hours. Electrical energy consumed in kWh?", a: "1 kWh", options: ["10 kWh", "1 kWh", "0.1 kWh", "100 kWh"] },
    { q: "Difference between the largest and smallest 3-digit numbers using 0, 2, 4?", a: "216", options: ["420", "216", "220", "440"] },
    { q: "Which mirror is used in car headlights?", a: "Concave", options: ["Convex", "Concave", "Plane", "None"] },
    { q: "Result of '5' + 3 in JavaScript?", a: "'53'", options: ["8", "'53'", "NaN", "Error"] },
    { q: "If tomorrow is 2 days after Sunday, what day was it yesterday?", a: "Sunday", options: ["Monday", "Tuesday", "Sunday", "Saturday"] },
    { q: "Which protocol uses only 2 wires (SDA/SCL)?", a: "I2C", options: ["SPI", "I2C", "UART", "USB"] },
    { q: "What does URL stand for?", a: "Uniform Resource Locator", options: ["Universal Road List", "Uniform Resource Locator", "United Radio Link", "None"] },
    { q: "A Silicon Diode has a saturation current of 10nA at 300K. What is the approximate forward voltage for a 10mA current?", a: "0.36 V", options: ["0.70 V", "0.36 V", "0.52 V", "0.85 V"] },
    { q: "Which nation chaired the 2025 BRICS summit where 5 new members were officially integrated?", a: "Brazil", options: ["Russia", "Brazil", "South Africa", "India"] },
    { q: "A boat goes 10km/h in still water. River speed 2km/h. Speed upstream?", a: "8 km/h", options: ["12 km/h", "8 km/h", "10 km/h", "6 km/h"] },
    { q: "If tomorrow is 2 days after Sunday, what day was it yesterday?", a: "Sunday", options: ["Monday", "Tuesday", "Sunday", "Saturday"] },
    { q: "Which component has 'Anode' and 'Cathode'?", a: "LED", options: ["Resistor", "LED", "Capacitor", "Switch"] },
    { q: "Probability of picking a non-vowel from the word 'ELECTRONICS'?", a: "7/11", options: ["4/11", "7/11", "1/2", "6/11"] },
    { q: "Unit of Force?", a: "Newton", options: ["Joule", "Watt", "Newton", "Pascal"] },
    { q: "A, B, C, D, E are in a row. A is next to B but not C. D is next to E. E is on left end. Position of B?", a: "2nd from left", options: ["2nd from left", "Center", "2nd from right", "Right end"] },
    { q: "Binary 101101 to Decimal?", a: "45", options: ["45", "43", "37", "41"] },
    { q: "Number of selection lines for a 1-to-32 Demultiplexer?", a: "5", options: ["4", "5", "16", "32"] },
    { q: "Introduction of a gardener plants 10 trees in 5 rows with 4 trees in each row. How?", a: "Star shape", options: ["Circle", "Star shape", "Square", "Impossible"] },
    { q: "The 2026 Winter Olympics (Milano Cortina) introduced which new sport?", a: "Ski Mountaineering", options: ["Padel", "Ski Mountaineering", "Cricket", "Squash"] },
    { q: "Which mirror is used in street lights to diverge light?", a: "Convex", options: ["Convex", "Concave", "Plane", "None"] },
    { q: "Which sorting algorithm has the best-case time complexity of O(N)?", a: "Insertion Sort", options: ["Quick Sort", "Merge Sort", "Insertion Sort", "Selection Sort"] },
    { q: "The 'CHIPS Act 2.0' (2025) primarily focuses on which technology?", a: "2nm Lithography", options: ["Quantum Computing", "2nm Lithography", "6G Networks", "Solid State Batteries"] },
    { q: "A clock loses 10 mins every hour. Set right at 12 PM. Real time is 6 PM. Clock time?", a: "5 PM", options: ["5 PM", "5:10 PM", "6:50 PM", "7 PM"] },
    { q: "How many cubic feet of dirt are in a hole 3ft deep, 3ft wide, and 3ft long?", a: "0", options: ["27", "9", "0", "3"] },
    { q: "If the radius of Earth is halved but mass is constant, what happens to 'g'?", a: "Increases 4x", options: ["Doubles", "Increases 4x", "Halves", "Constant"] },
    { q: "What is the cube root of 1728?", a: "12", options: ["12", "14", "16", "18"] },
    { q: "If 'POWER' is 77, what is 'WORK'?", a: "67", options: ["46", "67", "57", "68"] },
    { q: "The 'CHIPS Act 2.0' (2025) primarily focuses on which technology?", a: "2nm Lithography", options: ["Quantum Computing", "2nm Lithography", "6G Networks", "Solid State Batteries"] },
    { q: "Which currency officially overtook the Euro in global SWIFT payments in Q3 2025?", a: "Yuan (CNY)", options: ["Yuan (CNY)", "Yen (JPY)", "Pound (GBP)", "None"] },
    { q: "Seven people meet and each shakes hands with everyone else once. Total handshakes?", a: "21", options: ["49", "42", "21", "14"] },
    { q: "Binary equivalent of decimal 5?", a: "101", options: ["111", "110", "101", "011"] },
    { q: "Which element's isotope was successfully mined by the Chang'e-8 mission in 2025?", a: "Helium-3", options: ["Thorium", "Helium-3", "Lithium", "Uranium"] },
    { q: "If A+B means A is daughter of B, what is P+Q+R?", a: "P is granddaughter of R", options: ["P is sister", "P is granddaughter of R", "P is mother", "None"] },
    { q: "Introduction of a boy, Meena says: 'He is son of my father's only son.' Meena is his?", a: "Aunt", options: ["Mother", "Sister", "Aunt", "Grandmother"] },
    { q: "Probability of drawing a King or a Heart from a standard 52-card deck?", a: "16/52", options: ["17/52", "16/52", "13/52", "4/52"] },
    { q: "Binary 11111111 (8 bits) in Decimal?", a: "255", options: ["256", "255", "127", "254"] },
    { q: "Who was appointed as the first-ever 'Global Envoy for AI Safety' by the UN in late 2025?", a: "Demis Hassabis", options: ["Sam Altman", "Demis Hassabis", "Geoffrey Hinton", "Fei-Fei Li"] },
    { q: "Successive discounts of 20% and 10% equal?", a: "28%", options: ["30%", "28%", "25%", "22%"] },
    { q: "If A+B means A is daughter of B, what is P+Q+R?", a: "P is granddaughter of R", options: ["P is sister", "P is granddaughter of R", "P is mother", "None"] },
    { q: "Pointing to a man, a girl says: 'He is son of my grandfather's only child.' Who is he?", a: "Brother", options: ["Father", "Brother", "Cousin", "Uncle"] },
    { q: "Two mothers and two daughters go out to dinner. They only order 3 meals. Why?", a: "Grandmother, mother, daughter", options: ["Not hungry", "Baby", "Grandmother, mother, daughter", "Error"] },
    { q: "In 2026, which country became the first to implement a 'Global AI Sovereign Wealth Fund'?", a: "UAE", options: ["USA", "China", "UAE", "Saudi Arabia"] },
    { q: "The bandwidth of an amplifier with gain 100 and Gain-Bandwidth Product 1MHz?", a: "10 kHz", options: ["100 kHz", "10 kHz", "1 MHz", "1 kHz"] },
    { q: "Smallest unit of data in a computer?", a: "Bit", options: ["Bit", "Byte", "Nibble", "Pixel"] },
    { q: "Refractive index of water is 1.33. Speed of light in water?", a: "2.25 x 10^8 m/s", options: ["3 x 10^8 m/s", "2.25 x 10^8 m/s", "1.5 x 10^8 m/s", "2 x 10^8 m/s"] },
    { q: "M is the son of P. Q is the granddaughter of O, who is the husband of P. M is Q's?", a: "Father", options: ["Uncle", "Father", "Cousin", "Brother"] },
    { q: "Which space agency launched 'LUPEX' in 2025?", a: "ISRO & JAXA", options: ["NASA", "ISRO & JAXA", "ESA", "Roscosmos"] },
    { q: "The escape velocity from Earth's surface is approx?", a: "11.2 km/s", options: ["9.8 km/s", "11.2 km/s", "42 km/s", "7 km/s"] },
    { q: "How many letters are in 'The Alphabet'?", a: "11", options: ["26", "24", "11", "8"] },
    { q: "Pointing to a boy, Meena says: 'He is son of my father's only son.' Meena is his?", a: "Aunt", options: ["Mother", "Sister", "Aunt", "Grandmother"] },
    { q: "How many months have 28 days?", a: "12", options: ["1", "6", "12", "0"] },
    { q: "What does BIOS stand for?", a: "Basic Input Output System", options: ["Binary Input Output System", "Basic Input Output System", "Basic Integrated OS", "None"] },
    { q: "Which space agency launched the 'LUPEX' mission to the lunar south pole in 2025?", a: "ISRO & JAXA", options: ["NASA", "ISRO & JAXA", "ESA", "Roscosmos"] },
    { q: "A family has a man, wife, 3 sons and their wives, and 2 children each. Total?", a: "14", options: ["17", "14", "11", "20"] },
    { q: "Which color of light deviates the least through a prism?", a: "Red", options: ["Violet", "Blue", "Red", "Yellow"] },
    { q: "A cube's side is increased by 10%. By what percentage does the volume increase?", a: "33.1%", options: ["10%", "30%", "33.1%", "21%"] },
    { q: "Pointing to a lady, a man said: 'The son of her only brother is the brother of my wife.' Relationship?", a: "Sister of father-in-law", options: ["Maternal Aunt", "Sister of father-in-law", "Mother", "Sister"] },
    { q: "Which language is primarily used for Web styling?", a: "CSS", options: ["HTML", "Python", "CSS", "SQL"] },
    { q: "A is 300% of B. What percentage of A is B?", a: "33.33%", options: ["30%", "33.33%", "300%", "66.66%"] },
    { q: "If 1.1^x = 1.21, what is x?", a: "2", options: ["1", "2", "11", "1.1"] },
    { q: "If the power of a lens is +2.5D, what is its focal length?", a: "40 cm", options: ["25 cm", "40 cm", "50 cm", "10 cm"] },
    { q: "Sound travels fastest in?", a: "Steel", options: ["Air", "Water", "Steel", "Vacuum"] },
    { q: "I have branches, but no fruit, trunk, or leaves. What am I?", a: "A Bank", options: ["A Tree", "A River", "A Bank", "A Road"] },
    { q: "If 'CYBER' is 'EVDGT', how is 'VOLTS' coded?", a: "XQNUV", options: ["XQNUV", "WPMUT", "YRPWX", "XPMTV"] },
    { q: "What is seen in the middle of March and April but not at the start?", a: "The letter R", options: ["Spring", "Rain", "The letter R", "Sun"] },
    { q: "A Silicon Diode has a saturation current of 10nA at 300K. What is the approximate forward voltage for a 10mA current?", a: "0.36 V", options: ["0.70 V", "0.36 V", "0.52 V", "0.85 V"] },
    { q: "Where was the world's largest 'Carbon Capture' plant, 'Mammoth 2', commissioned in 2025?", a: "Iceland", options: ["Norway", "Iceland", "Canada", "USA"] },
    { q: "A boat goes 10km/h in still water. River speed 2km/h. Speed upstream?", a: "8 km/h", options: ["12 km/h", "8 km/h", "10 km/h", "6 km/h"] },
    { q: "Which gate inverts the input?", a: "NOT", options: ["AND", "OR", "NOT", "NAND"] },
    { q: "Who is the 'Father of Electronics'?", a: "Michael Faraday", options: ["Tesla", "Edison", "Faraday", "Maxwell"] },
    { q: "What color was it hunter walks 1km South, 1km East, and 1km North, ending up back at the start. He shot a bear?", a: "White", options: ["Brown", "Black", "White", "Grey"] },
    { q: "If you have a drawer with 10 black and 10 blue socks, what is the minimum you must pull to guarantee a matching pair?", a: "3", options: ["2", "3", "11", "21"] },
    { q: "Which scheduling algorithm can lead to Starvation?", a: "Priority", options: ["Round Robin", "Priority", "FIFO", "SJF"] },
    { q: "Equivalent resistance of an infinite ladder of 1Ω resistors?", a: "1.618 Ω", options: ["1 Ω", "2 Ω", "1.618 Ω", "0.5 Ω"] },
    { q: "What is the unit of electrical resistance?", a: "Ohm", options: ["Ampere", "Volt", "Ohm", "Watt"] },
    { q: "What is the efficiency of a Transformer at full load approx?", a: "95-98%", options: ["50%", "75%", "95-98%", "100%"] },
    { q: "If A+B means A is daughter of B, what is P+Q+R?", a: "P is granddaughter of R", options: ["P is sister", "P is granddaughter of R", "P is mother", "None"] },
    { q: "Which particle carries a negative charge?", a: "Electron", options: ["Proton", "Neutron", "Electron", "Positron"] },
    { q: "Number of edges in a complete graph with 10 vertices?", a: "45", options: ["90", "100", "45", "10"] },
    { q: "A clock loses 10 mins every hour. Set right at 12 PM. Real time is 6 PM. Clock time?", a: "5 PM", options: ["5 PM", "5:10 PM", "6:50 PM", "7 PM"] },
    { q: "What is the speed of light approx?", a: "3x10^8 m/s", options: ["3x10^6 m/s", "3x10^8 m/s", "1500 m/s", "3x10^10 m/s"] },
    { q: "Which logic gate is a 'Universal Gate'?", a: "NAND", options: ["AND", "OR", "NAND", "XOR"] },
    { q: "Introduction of a boy, Meena says: 'He is son of my father's only son.' Meena is his?", a: "Aunt", options: ["Mother", "Sister", "Aunt", "Grandmother"] },
    { q: "If you have a drawer with 10 black and 10 blue socks, what is the minimum you must pull to guarantee a matching pair?", a: "3", options: ["2", "3", "11", "21"] },
    { q: "Which sorting algorithm is O(n) in best case?", a: "Insertion Sort", options: ["Quick Sort", "Merge Sort", "Insertion Sort", "Selection Sort"] },
    { q: "Which IoT protocol uses a Publish/Subscribe model over TCP/IP?", a: "MQTT", options: ["HTTP", "MQTT", "CoAP", "LoRaWAN"] },
    { q: "In MQTT, which QoS level ensures a message is delivered exactly once?", a: "QoS 2", options: ["QoS 0", "QoS 1", "QoS 2", "QoS 3"] },
    { q: "What is the maximum payload size of a standard BLE (Bluetooth Low Energy) packet?", a: "31 bytes", options: ["31 bytes", "128 bytes", "256 bytes", "1024 bytes"] },
    { q: "Which communication protocol uses a 4-wire interface: MOSI, MISO, SCK, and SS?", a: "SPI", options: ["I2C", "UART", "SPI", "CAN"] },
    { q: "What is the standard frequency range for LoRaWAN in India?", a: "865-867 MHz", options: ["433 MHz", "865-867 MHz", "915 MHz", "2.4 GHz"] },
    { q: "In Zigbee architecture, which device is responsible for starting the network?", a: "Coordinator", options: ["Router", "End Device", "Coordinator", "Gateway"] },
    { q: "Which IoT protocol is specifically designed for constrained RESTful environments?", a: "CoAP", options: ["MQTT", "AMQP", "CoAP", "XMPP"] },
    { q: "What does the 'S' stand for in the HTTPS protocol for IoT security?", a: "Secure", options: ["Static", "Secure", "Socket", "Standard"] },
    { q: "Which Arduino board is based on the ATmega2560 microcontroller?", a: "Arduino Mega", options: ["Uno", "Nano", "Mega", "Due"] },
    { q: "What is the purpose of a 'Watchdog Timer' in an embedded system?", a: "Reset on hang", options: ["Measure time", "Reset on hang", "Save power", "Count pulses"] },
    { q: "Which sensor uses the Doppler effect to detect motion?", a: "Microwave Sensor", options: ["PIR Sensor", "Microwave Sensor", "Ultrasonic", "LDR"] },
    { q: "In I2C, how many devices can theoretically be connected using 7-bit addressing?", a: "128", options: ["128", "256", "1024", "64"] },
    { q: "Which protocol is primarily used for industrial automation and automotive applications?", a: "CAN Bus", options: ["Zigbee", "CAN Bus", "BLE", "Wi-Fi"] },
    { q: "What is the operating voltage of an ESP8266 Wi-Fi module?", a: "3.3V", options: ["5V", "3.3V", "12V", "1.8V"] },
    { q: "Which layer of the OSI model does a Gateway typically operate on?", a: "Application", options: ["Network", "Data Link", "Physical", "Application"] },
    { q: "What is the primary advantage of UDP over TCP in IoT data streaming?", a: "Lower Latency", options: ["Reliability", "Lower Latency", "Error Correction", "Handshaking"] },
    { q: "Which modulation technique is used by LoRa technology?", a: "CSS", options: ["FSK", "ASK", "CSS", "PSK"] },
    { q: "A pull-up resistor is used with a button to prevent which state?", a: "Floating", options: ["Short circuit", "Floating", "Overvoltage", "Grounding"] },
    { q: "What does 'IPv6' provide that is essential for the future of IoT?", a: "Address space", options: ["Speed", "Address space", "Encryption", "Battery life"] },
    { q: "In embedded C, which keyword prevents the compiler from optimizing a variable?", a: "volatile", options: ["static", "const", "volatile", "extern"] },
    { q: "Which cloud platform is specifically branded for IoT by Amazon?", a: "AWS IoT Core", options: ["Azure Hub", "AWS IoT Core", "Google Cloud", "IBM Watson"] },
    { q: "What is the typical range of an NRF24L01 transceiver module?", a: "100 meters", options: ["10 meters", "100 meters", "1 km", "5 km"] },
    { q: "Which characteristic of a battery is defined as 'C-rating'?", a: "Discharge rate", options: ["Capacity", "Voltage", "Discharge rate", "Internal R"] },
    { q: "Which IoT architecture layer handles data processing and decision making?", a: "Edge/Fog Layer", options: ["Perception", "Transport", "Edge/Fog Layer", "Physical"] },
    { q: "What is the bit depth of the built-in ADC on an Arduino Uno?", a: "10-bit", options: ["8-bit", "10-bit", "12-bit", "16-bit"] },

    // --- MATHEMATICAL REASONING & LOGIC TRAPS (25 Questions) ---
    { q: "A farmer has 10 stacks of hay in one field and 5 stacks in another. If he joins them, how many stacks does he have?", a: "1", options: ["15", "1", "5", "10"] },
    { q: "A clock strikes once at 1 o'clock, twice at 2, and so on. Total strikes in 24 hours?", a: "156", options: ["300", "78", "156", "144"] },
    { q: "If it takes 10 men 10 days to dig a hole, how long does it take 1 man to dig half a hole?", a: "Cannot dig half", options: ["5 days", "10 days", "100 days", "Cannot dig half"] },
    { q: "If you divide 30 by 0.5 and add 10, what is the result?", a: "70", options: ["25", "70", "15", "40"] },
    { q: "Some months have 30 days, some have 31. How many have 28?", a: "12", options: ["1", "12", "6", "0"] },
    { q: "What is the next number in the sequence: 1, 1, 2, 3, 5, 8, 13...?", a: "21", options: ["18", "20", "21", "25"] },
    { q: "A man is looking at a photo. 'Brothers and sisters I have none, but this man's father is my father's son.' Who is it?", a: "His son", options: ["Himself", "His son", "His father", "His nephew"] },
    { q: "A shirt is $100. It is discounted by 20%, then that price is increased by 20%. Final price?", a: "$96", options: ["$100", "$96", "$80", "$120"] },
    { q: "If 3 people can knit 3 socks in 3 days, how many days for 9 people to knit 9 socks?", a: "3", options: ["9", "3", "1", "27"] },
    { q: "You have 3 apples. You take away 2. How many apples do you have?", a: "2", options: ["1", "2", "3", "0"] },
    { q: "How many times can you subtract 5 from 25?", a: "Once", options: ["5", "Once", "Zero", "Infinite"] },
    { q: "Which is heavier: 100kg of iron or 100kg of feathers?", a: "Equal", options: ["Iron", "Feathers", "Equal", "Iron by a bit"] },
    { q: "A father is 4 times as old as his son. In 20 years, he will be twice as old. How old is the father now?", a: "40", options: ["32", "40", "48", "60"] },
    { q: "If 'BLUE' is 40, what is 'RED'?", a: "27", options: ["24", "27", "30", "18"] },
    { q: "A train 100m long passes a pole in 10 seconds. What is its speed in km/h?", a: "36 km/h", options: ["10 km/h", "36 km/h", "60 km/h", "100 km/h"] },
    { q: "What is the angle of a clock at 3:15?", a: "7.5 degrees", options: ["0", "7.5", "15", "22.5"] },
    { q: "Probability of picking a vowel from the word 'INTERNET'?", a: "3/8", options: ["3/8", "2/8", "1/2", "3/5"] },
    { q: "If 1=3, 2=3, 3=5, 4=4, 5=4, then 6=?", a: "3", options: ["6", "5", "3", "4"] },
    { q: "A doctor gives you 3 pills and tells you to take one every 30 minutes. How long do they last?", a: "60 minutes", options: ["90 mins", "60 mins", "30 mins", "120 mins"] },
    { q: "A room has 4 corners. A cat sits in each corner. Each cat sees 3 cats. How many cats?", a: "4", options: ["12", "4", "16", "3"] },
    { q: "How many 9s are there between 1 and 100?", a: "20", options: ["10", "11", "19", "20"] },
    { q: "If you have only one match and enter a cold room with a lamp, a heater, and a candle, which do you light first?", a: "The match", options: ["Lamp", "Heater", "Candle", "The match"] },
];


