const allQuestions = [
    // --- YOUR ORIGINAL 10 ---
    { q: "What is the unit of electric current?", a: "Ampere", options: ["Volt", "Watt", "Ampere", "Ohm"] },
    { q: "Which pin on Arduino Uno is used for analog read?", a: "A0", options: ["D13", "A0", "RESET", "TX"] },
    { q: "In C language, which symbol is used for comments?", a: "//", options: ["#", "//", "--", "/*"] },
    { q: "What is the chemical symbol for Silver?", a: "Ag", options: ["Si", "Au", "Ag", "Sl"] },
    { q: "What is the speed of light approx?", a: "3x10^8 m/s", options: ["3x10^6 m/s", "3x10^8 m/s", "1500 m/s", "3x10^10 m/s"] },
    { q: "Which function starts an Arduino program?", a: "setup()", options: ["start()", "main()", "setup()", "loop()"] },
    { q: "Power is equal to?", a: "Voltage x Current", options: ["V / I", "V + I", "Voltage x Current", "I / V"] },
    { q: "Which memory is volatile?", a: "RAM", options: ["ROM", "RAM", "HDD", "Flash"] },
    { q: "Founder of Microsoft?", a: "Bill Gates", options: ["Steve Jobs", "Elon Musk", "Bill Gates", "Jeff Bezos"] },
    { q: "What does CPU stand for?", a: "Central Processing Unit", options: ["Computer Personal Unit", "Central Processing Unit", "Central Peripheral Universal", "None"] },

    // --- ELECTRONICS & HARDWARE (11-25) ---
    { q: "Which component stores energy in a magnetic field?", a: "Inductor", options: ["Capacitor", "Resistor", "Inductor", "Diode"] },
    { q: "What is the resistance of an ideal voltmeter?", a: "Infinite", options: ["Zero", "100 Ohm", "Infinite", "1 Mega Ohm"] },
    { q: "Standard color for a Ground wire is usually?", a: "Green", options: ["Red", "Black", "Blue", "Green"] },
    { q: "A transistor acts primarily as a?", a: "Switch/Amplifier", options: ["Heater", "Switch/Amplifier", "Battery", "Filter"] },
    { q: "Which gate gives output 1 only if all inputs are 1?", a: "AND", options: ["OR", "AND", "NOR", "XOR"] },
    { q: "Unit of Inductance?", a: "Henry", options: ["Farad", "Henry", "Tesla", "Weber"] },
    { q: "IC stands for?", a: "Integrated Circuit", options: ["Internal Code", "Integrated Circuit", "Intelligent Chip", "Input Controller"] },
    { q: "What converts AC to DC?", a: "Rectifier", options: ["Inverter", "Rectifier", "Transformer", "Amplifier"] },
    { q: "Which metal is used in fuse wire?", a: "Tin-Lead alloy", options: ["Copper", "Iron", "Tin-Lead alloy", "Silver"] },
    { q: "Ohm's law formula?", a: "V = IR", options: ["V = I/R", "V = IR", "I = VR", "R = V+I"] },
    { q: "What is the binary equivalent of decimal 5?", a: "101", options: ["111", "110", "101", "011"] },
    { q: "A multimeter measures?", a: "All of these", options: ["Voltage", "Current", "Resistance", "All of these"] },
    { q: "Which component has 'Anode' and 'Cathode'?", a: "LED", options: ["Resistor", "LED", "Capacitor", "Switch"] },
    { q: "Capacity of a battery is measured in?", a: "mAh", options: ["Watts", "mAh", "Volts", "Ohms"] },
    { q: "Which sensor detects light?", a: "LDR", options: ["LDR", "PIR", "Ultrasonic", "Gyroscope"] },

    // --- COMPUTING & SOFTWARE (26-40) ---
    { q: "1 Byte is equal to how many bits?", a: "8 bits", options: ["4 bits", "8 bits", "16 bits", "32 bits"] },
    { q: "Which language is used for Web styling?", a: "CSS", options: ["HTML", "Python", "CSS", "SQL"] },
    { q: "Who is known as the father of AI?", a: "John McCarthy", options: ["Alan Turing", "John McCarthy", "Elon Musk", "Bill Gates"] },
    { q: "What does HTTP stand for?", a: "Hypertext Transfer Protocol", options: ["High Text Transfer Process", "Hypertext Transfer Protocol", "Hyper Transfer Text Path", "None"] },
    { q: "Python files have which extension?", a: ".py", options: [".pt", ".py", ".pyt", ".p"] },
    { q: "Which is not an Operating System?", a: "Google", options: ["Linux", "Windows", "Google", "Android"] },
    { q: "Full form of RAM?", a: "Random Access Memory", options: ["Read Any Memory", "Random Access Memory", "Real Audio Music", "Rapid Access Module"] },
    { q: "Which company owns Android?", a: "Google", options: ["Apple", "Microsoft", "Google", "Nokia"] },
    { q: "SQL is used for?", a: "Databases", options: ["Styling", "Databases", "Hardware", "Graphics"] },
    { q: "What is 'Bug' in computer terminology?", a: "An error", options: ["A virus", "An error", "A hardware part", "A small insect"] },
    { q: "The first computer mouse was made of?", a: "Wood", options: ["Plastic", "Metal", "Wood", "Glass"] },
    { q: "Which key is used to refresh a web page?", a: "F5", options: ["F2", "F5", "F11", "Esc"] },
    { q: "URL stands for?", a: "Uniform Resource Locator", options: ["Universal Road List", "Uniform Resource Locator", "United Radio Link", "None"] },
    { q: "A bit can be either?", a: "0 or 1", options: ["1 or 2", "0 or 1", "A or B", "High or Low"] },
    { q: "Commonly used language for IoT?", a: "C++", options: ["HTML", "C++", "CSS", "PHP"] },

    // --- PHYSICS & LOGIC (41-50) ---
    { q: "Unit of Force?", a: "Newton", options: ["Joule", "Watt", "Newton", "Pascal"] },
    { q: "Which mirror is used in car headlights?", a: "Concave", options: ["Convex", "Concave", "Plane", "None"] },
    { q: "Energy of motion is called?", a: "Kinetic", options: ["Potential", "Kinetic", "Static", "Thermal"] },
    { q: "Instrument to measure atmospheric pressure?", a: "Barometer", options: ["Thermometer", "Barometer", "Hygrometer", "Speedometer"] },
    { q: "The simplest form of logic circuit is?", a: "NOT gate", options: ["AND gate", "OR gate", "NOT gate", "XOR gate"] },
    { q: "What is the pH of pure water?", a: "7", options: ["0", "5", "7", "14"] },
    { q: "Who discovered Gravity?", a: "Isaac Newton", options: ["Einstein", "Newton", "Galileo", "Tesla"] },
    { q: "Which planet is known as the Red Planet?", a: "Mars", options: ["Venus", "Mars", "Jupiter", "Saturn"] },
    { q: "Sound travels fastest in?", a: "Steel", options: ["Air", "Water", "Steel", "Vacuum"] },
    { q: "Weight of an object is maximum at?", a: "Poles", options: ["Equator", "Poles", "Center of Earth", "Moon"] }
];